#cloud-config
packages:
 - sssd
 - realmd
 - oddjob
 - oddjob-mkhomedir
 - adcli
 - samba-common
 - samba-common-tools
 - krb5-workstation
 - openldap-clients
 - policycoreutils-python-utils

write_files:
 - path: /root/adjoin.sh
   permissions: '0700'
   owner: root:root
   content: |
    #!/bin/bash
    AD_SERVER=<ad server use_fully_qualified_names>
    AD_SERVER_IP=<IP address>
    ADMIN_DOMAIN=$AD_SERVER
    ADMIN_NAME=<Windows Domain Admin user name>
    ADMIN_PASSWORD=<Password>

    echo "nameserver ${AD_SERVER}" >> /etc/resolv.conf
    echo "${AD_SERVER_IP} ${AD_SERVER}" >> /etc/hosts

    sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config

    cat <<EOF >/etc/ssh/ssh_config
    Host *
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null
    EOF

    delay=15
    n=1
    max_retry=3

    while true; do
    logger -s "Domain join on $ADMIN_DOMAIN"
    echo $ADMIN_PASSWORD| realm join -U $ADMIN_NAME $ADMIN_DOMAIN

    if [ ! -f "/etc/sssd/sssd.conf" ]; then
    if [[ $n -le $max_retry ]]; then
    logger -s "Failed to domain join the server - Attempt $n/$max_retry:"
    sleep $delay
    ((n++))
    else
    logger -s "Failed to domain join the server after $n attempts."
    exit 1
    fi
    else
    logger -s "Successfully joined domain $ADMIN_DOMAIN"
    realm list
    break
    fi
    done

    sed -i 's@use_fully_qualified_names.*@use_fully_qualified_names = False@' /etc/sssd/sssd.conf
    sed -i 's@ldap_id_mapping.*@ldap_id_mapping = True@' /etc/sssd/sssd.conf
    sed -i 's@fallback_homedir.*@fallback_homedir = /shared/home/%u@' /etc/sssd/sssd.conf

    systemctl restart sssd
    systemctl restart sshd

    # Check if we are domain joined
    realm list | grep active-directory
    if [ $? -eq 1 ]; then
    logger -s "Node $(hostname) is not domain joined"
    exit 1
    fi

runcmd:
 - sh /root/adjoin.sh 2>&1>/root/logs.txt